require("config.globals")
require("config.keymaps")
require("config.options")
require("config.autocmds")
require("config.lsp")
require("config.lazy")
require("config.colorscheme")
require("utils.folds")
